version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=ChatAppDb;User=root;Password=1234;Port=3306
    depends_on:
      - mysql
    networks:
      - chitchat-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ChatAppDb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chitchat-network

networks:
  chitchat-network:
    driver: bridge

volumes:
  mysql-data: 